### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by trods85** [fstltna/ImpFE#1]
When I try to open the ship or planet dialogue I get this.

Program received signal SIGSEGV, Segmentation fault.
strlen () at ../sysdeps/x86_64/strlen.S:106
106 ../sysdeps/x86_64/strlen.S: No such file or directory.

**Comment by trods85** [comment]
(gdb) where
#0  strlen () at ../sysdeps/x86_64/strlen.S:106
#1  0x00007ffff6dbfbd5 in __strcpy_chk (
    dest=0x7fffffffe4a0 <incomplete sequence \337>, 
    src=0xfffffffff706fa20 <error: Cannot access memory at address 0xfffffffff706fa20>, destlen=28) at strcpy_chk.c:28
#2  0x0000000000417433 in strcpy (__src=<optimized out>, 
    __dest=0x7fffffffe4a0 <incomplete sequence \337>)
    at /usr/include/x86_64-linux-gnu/bits/string3.h:110
#3  buildShCensus () at ship.c:112
#4  0x000000000040bece in MainViewMenu_cb (ob=<optimized out>, 
    data=<optimized out>) at gui_cb.c:226
#5  0x00007ffff7505fe7 in fli_object_qread () from /usr/lib/libforms.so.2
#6  0x00007ffff751dd88 in fl_do_forms () from /usr/lib/libforms.so.2
#7  0x00000000004035ea in main (argc=1, argv=<optimized out>) at main.c:392

**Comment by fstltna** [comment]
Should be fixed. Was partially due to the -O2 flag breaking on some platforms...
